NAME		= Polymorphism Animal.cpp Dog.cpp Cat.cpp
SRC			= main.cpp
OBJ			= ${SRC:.cpp=.o}
CXXFLAGS	= -Wall -Wextra -Werror -std=c++98
RM			= rm -rf

all: $(NAME)

$(NAME): $(OBJ)
	c++ $(OBJ) $(CXXFLAGS) -o $(NAME)

clean:
	$(RM) (OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re